# Generated by Django 3.0.5 on 2020-04-12 03:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0002_auto_20200412_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee', models.CharField(max_length=225)),
                ('joining_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Designation')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Section')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photo/')),
                ('Father_name', models.CharField(max_length=225)),
                ('Mother_name', models.CharField(max_length=225)),
                ('personal_mobile_number', models.CharField(max_length=17, unique=True)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=17)),
                ('date_of_birth', models.DateField(default='1900-01-01')),
                ('national_id', models.CharField(default='', max_length=20, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('present_address', models.TextField(blank=True, max_length=300, null=True)),
                ('permanant_address', models.TextField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('blood_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.BloodGroup')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Country')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Division')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Employee')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Gender')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Religion')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.DateField(default=datetime.datetime.now)),
                ('time_in', models.TimeField(default=datetime.datetime.now)),
                ('time_out', models.TimeField(default=datetime.datetime.now)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Employee')),
            ],
        ),
    ]
