# Generated by Django 3.0.5 on 2020-04-12 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0004_auto_20200412_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
