# Generated by Django 3.0.5 on 2020-04-12 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0005_auto_20200412_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
