# Generated by Django 3.0.5 on 2020-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0007_attendance_attendance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
