# Generated by Django 3.0.5 on 2020-04-12 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0009_auto_20200412_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
